/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'macId' : string,
  'status' : string,
  'purchaseDate' : string,
  'serviceTag' : string,
  'vendor' : string,
  'notes' : string,
  'lastServiceDate' : string,
  'category' : string,
  'assetName' : string,
  'department' : string,
}
export interface _SERVICE {
  'addAsset' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'addOption' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteAsset' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'getAsset' : ActorMethod<[bigint], [] | [Asset]>,
  'getAssets' : ActorMethod<[], Array<Asset>>,
  'getOptions' : ActorMethod<[string], Array<string>>,
  'removeOption' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateAsset' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOption' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];