/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Printer' : IDL.Null,
  'Phone' : IDL.Null,
  'Computer' : IDL.Null,
  'Software' : IDL.Null,
  'Monitor' : IDL.Null,
  'Peripheral' : IDL.Null,
  'Other' : IDL.Null,
  'NetworkDevice' : IDL.Null,
});
export const Status = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'InRepair' : IDL.Null,
  'Retired' : IDL.Null,
});
export const Department = IDL.Variant({
  'HR' : IDL.Null,
  'IT' : IDL.Null,
  'Engineering' : IDL.Null,
  'Accounts' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Other' : IDL.Null,
  'Biomedical' : IDL.Null,
  'Finance' : IDL.Null,
  'Administration' : IDL.Null,
});
export const ITAsset = IDL.Record({
  'id' : IDL.Nat,
  'macId' : IDL.Text,
  'status' : Status,
  'purchaseVendor' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'name' : IDL.Text,
  'serviceTag' : IDL.Text,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'lastServiceDate' : IDL.Text,
  'category' : Category,
  'assignedDepartment' : Department,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAsset' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Status,
        Department,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(ITAsset)], ['query']),
  'getAsset' : IDL.Func([IDL.Nat], [ITAsset], ['query']),
  'getAssetName' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Printer' : IDL.Null,
    'Phone' : IDL.Null,
    'Computer' : IDL.Null,
    'Software' : IDL.Null,
    'Monitor' : IDL.Null,
    'Peripheral' : IDL.Null,
    'Other' : IDL.Null,
    'NetworkDevice' : IDL.Null,
  });
  const Status = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'InRepair' : IDL.Null,
    'Retired' : IDL.Null,
  });
  const Department = IDL.Variant({
    'HR' : IDL.Null,
    'IT' : IDL.Null,
    'Engineering' : IDL.Null,
    'Accounts' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Other' : IDL.Null,
    'Biomedical' : IDL.Null,
    'Finance' : IDL.Null,
    'Administration' : IDL.Null,
  });
  const ITAsset = IDL.Record({
    'id' : IDL.Nat,
    'macId' : IDL.Text,
    'status' : Status,
    'purchaseVendor' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'name' : IDL.Text,
    'serviceTag' : IDL.Text,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'lastServiceDate' : IDL.Text,
    'category' : Category,
    'assignedDepartment' : Department,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addAsset' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Status,
          Department,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(ITAsset)], ['query']),
    'getAsset' : IDL.Func([IDL.Nat], [ITAsset], ['query']),
    'getAssetName' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };