/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'macId' : IDL.Text,
  'status' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'serviceTag' : IDL.Text,
  'vendor' : IDL.Text,
  'notes' : IDL.Text,
  'lastServiceDate' : IDL.Text,
  'category' : IDL.Text,
  'assetName' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAsset' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addOption' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteAsset' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
  'getAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getOptions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'removeOption' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateAsset' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateOption' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'macId' : IDL.Text,
    'status' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'serviceTag' : IDL.Text,
    'vendor' : IDL.Text,
    'notes' : IDL.Text,
    'lastServiceDate' : IDL.Text,
    'category' : IDL.Text,
    'assetName' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'addAsset' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addOption' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteAsset' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
    'getAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getOptions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'removeOption' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateAsset' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateOption' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };