/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Printer' : null } |
  { 'Phone' : null } |
  { 'Computer' : null } |
  { 'Software' : null } |
  { 'Monitor' : null } |
  { 'Peripheral' : null } |
  { 'Other' : null } |
  { 'NetworkDevice' : null };
export type Department = { 'HR' : null } |
  { 'IT' : null } |
  { 'Engineering' : null } |
  { 'Accounts' : null } |
  { 'Maintenance' : null } |
  { 'Other' : null } |
  { 'Biomedical' : null } |
  { 'Finance' : null } |
  { 'Administration' : null };
export interface ITAsset {
  'id' : bigint,
  'macId' : string,
  'status' : Status,
  'purchaseVendor' : string,
  'purchaseDate' : string,
  'name' : string,
  'serviceTag' : string,
  'serialNumber' : string,
  'notes' : string,
  'lastServiceDate' : string,
  'category' : Category,
  'assignedDepartment' : Department,
  'location' : string,
}
export type Status = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'InRepair' : null } |
  { 'Retired' : null };
export interface UpdateAssetParams {
  'id' : bigint,
  'macId' : string,
  'status' : Status,
  'purchaseVendor' : string,
  'purchaseDate' : string,
  'name' : string,
  'serviceTag' : string,
  'serialNumber' : string,
  'notes' : string,
  'lastServiceDate' : string,
  'category' : Category,
  'assignedDepartment' : Department,
  'location' : string,
}
export interface _SERVICE {
  'addAsset' : ActorMethod<
    [
      string,
      Category,
      string,
      string,
      string,
      Status,
      Department,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'getAllAssets' : ActorMethod<[], Array<ITAsset>>,
  'getAsset' : ActorMethod<[bigint], ITAsset>,
  'getAssetName' : ActorMethod<[bigint], [] | [string]>,
  'updateAsset' : ActorMethod<
    [UpdateAssetParams],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];